server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: im-core

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/IM?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    host: 127.0.0.1
    port: 6380
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10
    database: 0
#
#
#  rabbitmq:
#    host: 43.138.58.95
#    port: 5672
#    addresses: 43.138.58.95
#    username: root
#    password: lige0612
#    #    virtual-host:
#    listener:
#      simple:
#        concurrency: 5
#        max-concurrency: 10
#        acknowledge-mode: MANUAL
#        prefetch: 1
#    publisher-returns: true
#    template:
#      mandatory: true
#    cache:
#      connection:
#        mode: channel
#      channel:
#        size: 36




#        checkout-timeout: 0

appConfig:
  privateKey: 123456
  zkAddr: 43.138.58.95:2181 # zk连接地址
  zkConnectTimeOut: 10000 # zk超时连接
  imRouteWay: 3 # 路由策略1轮训 2随机 3hash
  consistentHashWay: 1 # 如果选用一致性hash的话具体hash算法 1 TreeMap 2 自定义Map
  callbackUrl: http://127.0.0.1:8989/callback
  sendMessageCheckFriend: false # 发送消息是否校验关系链
  sendMessageCheckBlack: false # 发送消息是否校验黑名单
  modifyUserAfterCallback: false # 用户资料变更之后回调开关
  addFriendAfterCallback: false # 添加好友之后回调开关
  addFriendBeforeCallback: false # 添加好友之前回调开关
  modifyFriendAfterCallback: false # 修改好友之后回调开关
  deleteFriendAfterCallback: false # 删除好友之后回调开关
  addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
  deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
  createGroupAfterCallback: false # 创建群聊之后回调开关
  modifyGroupAfterCallback: false # 修改群聊之后回调开关
  destroyGroupAfterCallback: false # 解散群聊之后回调开关
  deleteGroupMemberAfterCallback: false # 删除群成员之后回调
  addGroupMemberAfterCallback: false # 拉人入群之后回调
  addGroupMemberBeforeCallback: false # 拉人入群之前回调
  sendMessageAfterCallback: false # 发送单聊消息之后
  sendMessageBeforeCallback: false # 发送单聊消息之前
  sendGroupMessageAfterCallback: false # 发送群聊消息之后
  sendGroupMessageBeforeCallback: false # 发送群聊消息之前
  offlineMessageCount: 1000 #离线消息存储条数
  deleteConversationSyncMode: 1 #1多段同步
# logger ??



logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY
#mybatis:
#  configuration:

#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

